import type { IFormControl } from "@/components/auth/formTypes";
import type { IKnowlageBase } from "@/components/knowlageBase/knowlageBaseTypes";
import type { IDoc } from "@/components/myDocuments/docTypes";

export const knowlageBaseData: IKnowlageBase[] = [
  {
    id: "1",
    title: "Федеральный закон № 152-ФЗ",
    description: "О персональных данных",
    lastUpdated: "15.05.2022",
    status: "Активный",
    link: "https://www.consultant.ru/document/cons_doc_LAW_140620/",
  },
  {
    id: "2",
    title: "ГОСТ Р 34.10-2012",
    description: "Информационная технология. Криптографическая защита информации.",
    lastUpdated: "03.11.2021",
    status: "Активный",
    link: "https://www.gost.ru/wps/portal/pages/gost/home",
  },
  {
    id: "3",
    title: "Федеральный закон № 63-ФЗ",
    description: "Об электронной подписи",
    lastUpdated: "20.01.2023",
    status: "Активный",
    link: "https://www.consultant.ru/document/cons_doc_LAW_140620/",
  },
  {
    id: "4",
    title: "Приказ ФСБ России № 378",
    description: "Об утверждении Положения о средствах шифрования",
    lastUpdated: "12.08.2022",
    status: "Активный",
    link: "https://www.fsb.ru/fsb/press/press-release/2022/08/12/378",
  },
  {
    id: "5",
    title: "Федеральный закон № 149-ФЗ",
    description: "Об информации, информационных технологиях и о защите информации",
    lastUpdated: "05.03.2023",
    status: "Активный",
    link: "https://www.consultant.ru/document/cons_doc_LAW_140620/",
  },
  {
    id: "6",
    title: "ГОСТ Р 58833-2020",
    description:
      "Защита информации. Требования к безопасности систем электронного документооборота",
    lastUpdated: "12.04.2024",
    status: "Активный",
    link: "https://www.gost.ru/wps/portal/pages/gost/home",
  },
  {
    id: "7",
    title: "Приказ ФСТЭК России № 239",
    description: "Требования по обеспечению безопасности значимых объектов КИИ",
    lastUpdated: "15.04.2024",
    status: "Активный",
    link: "https://www.fstek.ru/documents/239",
  },
  {
    id: "8",
    title: "СанПиН 2.2.2/2.4.1340-03",
    description: "Гигиенические требования к персональным электронно-вычислительным машинам",
    lastUpdated: "10.04.2024",
    status: "Неактивный",
    link: "https://www.rospotrebnadzor.ru/documents/details.php?ELEMENT_ID=12345",
  },
  {
    id: "9",
    title: "ГОСТ Р 34.12-2020",
    description: "Информационная технология. Криптографическая защита информации. Блочные шифры",
    lastUpdated: "08.04.2024",
    status: "Активный",
    link: "https://www.gost.ru/wps/portal/pages/gost/home",
  },
  {
    id: "10",
    title: "Федеральный закон № 187-ФЗ",
    description: "О безопасности критической информационной инфраструктуры РФ",
    lastUpdated: "05.04.2024",
    status: "Активный",
    link: "https://www.consultant.ru/document/cons_doc_LAW_140620/",
  },
  {
    id: "11",
    title: "Приказ ФСБ России № 796",
    description: "Требования к средствам электронной подписи",
    lastUpdated: "01.04.2024",
    status: "Активный",
    link: "https://www.fsb.ru/fsb/press/press-release/2024/04/01/796",
  },
  {
    id: "12",
    title: "ГОСТ Р 57580.1-2017",
    description: "Безопасность финансовых операций. Защита информации финансовых организаций",
    lastUpdated: "28.03.2024",
    status: "Активный",
    link: "https://www.gost.ru/wps/portal/pages/gost/home",
  },
  {
    id: "13",
    title: "Приказ Минкомсвязи № 486",
    description: "Требования к оператору электронного документооборота",
    lastUpdated: "25.03.2024",
    status: "Неактивный",
    link: "https://www.minsvyaz.ru/press/486",
  },
  {
    id: "14",
    title: "ГОСТ Р ИСО/МЭК 27001-2021",
    description: "Методы и средства обеспечения безопасности. Системы менеджмента ИБ",
    lastUpdated: "20.03.2024",
    status: "Активный",
    link: "https://www.gost.ru/wps/portal/pages/gost/home",
  },
  {
    id: "15",
    title: "Федеральный закон № 98-ФЗ",
    description: "О коммерческой тайне",
    lastUpdated: "18.03.2024",
    status: "Активный",
    link: "https://www.consultant.ru/document/cons_doc_LAW_140620/",
  },
  {
    id: "16",
    title: "ГОСТ Р 54581-2011",
    description: "Информационная технология. Методы и средства обеспечения безопасности",
    lastUpdated: "15.03.2024",
    status: "Активный",
    link: "https://www.gost.ru/wps/portal/pages/gost/home",
  },
  {
    id: "17",
    title: "Приказ ФСТЭК России № 17",
    description: "Требования о защите информации, не составляющей государственную тайну",
    lastUpdated: "12.03.2024",
    status: "Активный",
    link: "https://www.fstek.ru/documents/17",
  },
  {
    id: "18",
    title: "ГОСТ Р 58412-2019",
    description: "Защита информации. Разработка безопасного программного обеспечения",
    lastUpdated: "10.03.2024",
    status: "Активный",
    link: "https://www.gost.ru/wps/portal/pages/gost/home",
  },
  {
    id: "19",
    title: "Федеральный закон № 162-ФЗ",
    description: "О стандартизации в Российской Федерации",
    lastUpdated: "08.03.2024",
    status: "Активный",
    link: "https://www.consultant.ru/document/cons_doc_LAW_140620/",
  },
  {
    id: "20",
    title: "ГОСТ Р 51583-2014",
    description: "Защита информации. Порядок создания автоматизированных систем",
    lastUpdated: "05.03.2024",
    status: "Активный",
    link: "https://www.gost.ru/wps/portal/pages/gost/home",
  },
];

export const testDocuments: IDoc[] = [
  {
    id: "1",
    name: "ТЗ на разработку системы учета",
    uploadDate: "15.03.2024",
    status: "Проанализировано",
    size: "1.2 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "2",
    name: "Спецификация мобильного приложения",
    uploadDate: "02.04.2024",
    status: "Ожидает анализа",
    size: "3.5 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "3",
    name: "ТЗ на разработку CRM системы",
    uploadDate: "10.04.2024",
    status: "Ожидает анализа",
    size: "2.1 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "4",
    name: "Спецификация веб-портала",
    uploadDate: "05.04.2024",
    status: "Проанализировано",
    size: "4.7 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "5",
    name: "ТЗ на модуль аналитики",
    uploadDate: "01.04.2024",
    status: "Проанализировано",
    size: "1.8 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "6",
    name: "ТЗ на систему документооборота",
    uploadDate: "12.03.2024",
    status: "Проанализировано",
    size: "2.3 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "7",
    name: "Спецификация платежного модуля",
    uploadDate: "20.03.2024",
    status: "Ожидает анализа",
    size: "1.9 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "8",
    name: "Спецификация модуля интеграции",
    uploadDate: "15.03.2024",
    status: "Проанализировано",
    size: "2.4 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "9",
    name: "ТЗ на мобильное приложение",
    uploadDate: "18.03.2024",
    status: "Ожидает анализа",
    size: "3.1 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "10",
    name: "Спецификация API",
    uploadDate: "22.03.2024",
    status: "Проанализировано",
    size: "1.7 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "11",
    name: "ТЗ на модуль статистики",
    uploadDate: "24.03.2024",
    status: "Ожидает анализа",
    size: "2.9 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "12",
    name: "Спецификация системы уведомлений",
    uploadDate: "26.03.2024",
    status: "Проанализировано",
    size: "2.2 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "13",
    name: "ТЗ на модуль авторизации",
    uploadDate: "27.03.2024",
    status: "Ожидает анализа",
    size: "1.6 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "14",
    name: "Спецификация чат-бота",
    uploadDate: "29.03.2024",
    status: "Проанализировано",
    size: "2.5 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "15",
    name: "ТЗ на модуль отчетов",
    uploadDate: "30.03.2024",
    status: "Ожидает анализа",
    size: "3.3 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "16",
    name: "Спецификация админ-панели",
    uploadDate: "31.03.2024",
    status: "Проанализировано",
    size: "2.7 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "17",
    name: "ТЗ на модуль аналитики",
    uploadDate: "01.04.2024",
    status: "Ожидает анализа",
    size: "2.0 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "18",
    name: "Спецификация поисковой системы",
    uploadDate: "02.04.2024",
    status: "Проанализировано",
    size: "3.4 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "19",
    name: "ТЗ на модуль экспорта",
    uploadDate: "03.04.2024",
    status: "Ожидает анализа",
    size: "1.5 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "20",
    name: "Спецификация модуля импорта",
    uploadDate: "04.04.2024",
    status: "Проанализировано",
    size: "2.6 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "21",
    name: "ТЗ на систему логирования",
    uploadDate: "05.04.2024",
    status: "Ожидает анализа",
    size: "1.9 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "22",
    name: "Спецификация модуля безопасности",
    uploadDate: "06.04.2024",
    status: "Проанализировано",
    size: "3.0 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "23",
    name: "ТЗ на модуль интеграции",
    uploadDate: "07.04.2024",
    status: "Ожидает анализа",
    size: "2.3 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "24",
    name: "Спецификация модуля уведомлений",
    uploadDate: "08.04.2024",
    status: "Проанализировано",
    size: "2.8 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "25",
    name: "ТЗ на модуль статистики",
    uploadDate: "09.04.2024",
    status: "Ожидает анализа",
    size: "3.2 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "26",
    name: "Спецификация модуля отчетности",
    uploadDate: "10.04.2024",
    status: "Проанализировано",
    size: "2.1 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "27",
    name: "ТЗ на модуль аналитики",
    uploadDate: "11.04.2024",
    status: "Ожидает анализа",
    size: "2.5 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "28",
    name: "Спецификация модуля авторизации",
    uploadDate: "12.04.2024",
    status: "Проанализировано",
    size: "1.8 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "29",
    name: "ТЗ на модуль поиска",
    uploadDate: "13.04.2024",
    status: "Ожидает анализа",
    size: "2.7 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "30",
    name: "Спецификация модуля экспорта",
    uploadDate: "14.04.2024",
    status: "Проанализировано",
    size: "3.1 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "31",
    name: "ТЗ на модуль импорта",
    uploadDate: "15.04.2024",
    status: "Ожидает анализа",
    size: "2.4 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "32",
    name: "Спецификация модуля логирования",
    uploadDate: "16.04.2024",
    status: "Проанализировано",
    size: "2.0 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "33",
    name: "ТЗ на модуль безопасности",
    uploadDate: "17.04.2024",
    status: "Ожидает анализа",
    size: "2.9 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "34",
    name: "Спецификация модуля интеграции",
    uploadDate: "18.04.2024",
    status: "Проанализировано",
    size: "2.2 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "35",
    name: "ТЗ на модуль уведомлений",
    uploadDate: "19.04.2024",
    status: "Ожидает анализа",
    size: "2.6 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "36",
    name: "Спецификация модуля статистики",
    uploadDate: "20.04.2024",
    status: "Проанализировано",
    size: "3.3 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "37",
    name: "ТЗ на модуль отчетности",
    uploadDate: "21.04.2024",
    status: "Ожидает анализа",
    size: "1.7 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "38",
    name: "Спецификация модуля аналитики",
    uploadDate: "22.04.2024",
    status: "Проанализировано",
    size: "2.8 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "39",
    name: "ТЗ на модуль авторизации",
    uploadDate: "23.04.2024",
    status: "Ожидает анализа",
    size: "2.3 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "40",
    name: "Спецификация модуля поиска",
    uploadDate: "24.04.2024",
    status: "Проанализировано",
    size: "3.0 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "41",
    name: "ТЗ на модуль экспорта",
    uploadDate: "25.04.2024",
    status: "Ожидает анализа",
    size: "1.9 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "42",
    name: "Спецификация модуля импорта",
    uploadDate: "26.04.2024",
    status: "Проанализировано",
    size: "2.5 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "43",
    name: "ТЗ на модуль логирования",
    uploadDate: "27.04.2024",
    status: "Ожидает анализа",
    size: "2.1 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "44",
    name: "Спецификация модуля безопасности",
    uploadDate: "28.04.2024",
    status: "Проанализировано",
    size: "3.2 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "45",
    name: "ТЗ на модуль интеграции",
    uploadDate: "29.04.2024",
    status: "Ожидает анализа",
    size: "2.4 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "46",
    name: "Спецификация модуля уведомлений",
    uploadDate: "30.04.2024",
    status: "Проанализировано",
    size: "2.7 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "47",
    name: "ТЗ на систему мониторинга",
    uploadDate: "25.03.2024",
    status: "Проанализировано",
    size: "2.8 МБ",
    link: "/pdf-test.pdf",
  },
  {
    id: "48",
    name: "Спецификация модуля отчетности",
    uploadDate: "28.03.2024",
    status: "Ожидает анализа",
    size: "3.2 МБ",
    link: "/pdf-test.pdf",
  },
];

export const formControls: IFormControl[] = [
  {
    label: "Имя",
    name: "name",
    placeholder: "Введите имя",
    type: "text",
  },
  {
    label: "Email",
    name: "email",
    placeholder: "Введите email",
    type: "email",
  },
  {
    label: "Пароль",
    name: "password",
    placeholder: "Введите пароль",
    type: "password",
  },
  {
    label: "Подтвердите пароль",
    name: "confirmPassword",
    placeholder: "Повторите пароль",
    type: "password",
  },
];
